# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Brief project summary"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        help_text="Current project status",
                        max_length=20,
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Project complexity level",
                        max_length=20,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, help_text="Game genre", max_length=100, null=True
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, help_text="Game theme", max_length=100, null=True
                    ),
                ),
                (
                    "world_size",
                    models.CharField(
                        default="medium", help_text="World size setting", max_length=50
                    ),
                ),
                (
                    "settings",
                    models.JSONField(default=dict, help_text="Project settings"),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Project metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Project owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
