# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="starting_canvas",
            field=models.ForeignKey(
                blank=True,
                help_text="Default starting canvas for this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_starting",
                to="stories.storycanvas",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="projects_pr_owner_i_4798b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="projects_pr_created_6b02e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
    ]
