# Generated by Django 5.0.1 on 2025-11-04 23:05

import uuid
from django.db import connection, migrations, models

def _array_or_json(**kwargs):
    """Use ArrayField on PostgreSQL, JSONField on SQLite."""
    if connection.vendor == "postgresql":
        import django.contrib.postgres.fields
        return _array_or_json(**kwargs)
    kwargs.pop("base_field", None)
    kwargs.pop("size", None)
    return models.JSONField(**kwargs)

def _search_vector_or_text(**kwargs):
    """Use SearchVectorField on PostgreSQL, TextField on SQLite."""
    if connection.vendor == "postgresql":
        import django.contrib.postgres.search
        return _search_vector_or_text(**kwargs)
    return models.TextField(**kwargs)

def _vector_or_text(**kwargs):
    """Use VectorField on PostgreSQL, TextField on SQLite."""
    if connection.vendor == "postgresql":
        from pgvector.django import VectorField
        return _vector_or_text(**kwargs)
    kwargs.pop("dimensions", None)
    return models.TextField(**kwargs)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # Ensure pgvector extension is available (PostgreSQL only, no-op on SQLite)
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;" if connection.vendor == "postgresql" else "SELECT 1;",
            reverse_sql="SELECT 1;",
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("episodic", "Episodic (user interactions)"),
                            ("semantic", "Semantic (stable facts)"),
                            ("feedback", "Feedback (critiques/preferences)"),
                            ("artifacts", "Artifacts (outlines/drafts)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Main topic/theme of memory", max_length=100
                    ),
                ),
                ("text", models.TextField(help_text="Memory content/description")),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for retrieval"
                    ),
                ),
                (
                    "refs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="References to canvas/node/location IDs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ttl_days",
                    models.IntegerField(default=90, help_text="Time to live in days"),
                ),
            ],
            options={
                "db_table": "elora_agent_memories",
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("think", "Thinker Mode (brainstorm, critique, reflect)"),
                            ("do", "Doer Mode (execute tools, patch canvases)"),
                        ],
                        default="think",
                        max_length=10,
                    ),
                ),
                (
                    "user_goal",
                    models.TextField(
                        blank=True, help_text="Current user goal/objective"
                    ),
                ),
                (
                    "context_snippets",
                    models.JSONField(
                        blank=True, default=list, help_text="Retrieved context snippets"
                    ),
                ),
                (
                    "feedback_topics",
                    models.JSONField(
                        blank=True, default=list, help_text="Active feedback topics"
                    ),
                ),
                (
                    "last_tool",
                    models.CharField(
                        blank=True, help_text="Last tool called", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "elora_agent_sessions",
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "edge_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "predicate",
                    models.CharField(
                        choices=[
                            ("USES_LOCATION", "Uses Location"),
                            ("HAS_CHARACTER", "Has Character"),
                            ("LINKS_TO", "Links To"),
                            ("TRIGGERS", "Triggers"),
                            ("BELONGS_TO", "Belongs To"),
                            ("DERIVES_FROM", "Derives From"),
                            ("MENTIONS", "Mentions"),
                            ("CONTAINS", "Contains"),
                            ("HAS_TRIGGER", "Has Trigger"),
                            ("LOCATED_AT", "Located At"),
                            ("HAS_SCHEDULE", "Has Schedule"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0, help_text="Relationship strength/importance"
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Evidence of relationship (field path, text span, etc.)",
                    ),
                ),
                (
                    "version_range",
                    _array_or_json(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text="Version range where this relationship applies",
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "elora_edges",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "entity_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("canvas", "Story Canvas"),
                            ("location", "World Location"),
                            ("character", "Character"),
                            ("npc", "Non-Player Character"),
                            ("memory", "Agent Memory"),
                            ("project", "Project"),
                            ("trigger", "Canvas Trigger"),
                            ("schedule", "Trigger Schedule"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("version", models.IntegerField(default=1)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short description for display"
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Denormalized snapshot for search",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Searchable text concatenation"
                    ),
                ),
                (
                    "tags",
                    _array_or_json(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Tags for filtering and search",
                        size=None,
                    ),
                ),
                (
                    "search_vector",
                    _search_vector_or_text(
                        blank=True,
                        help_text="PostgreSQL tsvector for BM25 full-text search",
                        null=True,
                    ),
                ),
                (
                    "embedding",
                    _vector_or_text(
                        blank=True,
                        dimensions=1536,
                        help_text="OpenAI semantic embedding vector for similarity search",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "elora_entities",
            },
        ),
    ]
