# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("elora_simplified", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmemory",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_memories",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_sessions",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="edge",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="edge",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_edges",
                to="elora_simplified.entity",
            ),
        ),
        migrations.AddField(
            model_name="edge",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_edges",
                to="elora_simplified.entity",
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["project", "kind", "created_at"],
                name="elora_agent_project_c4e737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["project", "topic"], name="elora_agent_project_3f0b0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["created_at"], name="elora_agent_created_97ea34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["project", "user", "is_active"],
                name="elora_agent_project_4144ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["is_active", "updated_at"],
                name="elora_agent_is_acti_3995ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["project", "entity_type"], name="elora_entit_project_c98eae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["project", "slug"], name="elora_entit_project_47d25a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["project", "entity_type", "name"],
                name="elora_entit_project_e3d755_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["project", "entity_type", "updated_at"],
                name="elora_entit_project_9990b5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together={("project", "entity_type", "slug")},
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["subject", "predicate"], name="elora_edges_subject_e0fd80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["object", "predicate"], name="elora_edges_object__2a71a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["project", "predicate"], name="elora_edges_project_bef419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["predicate", "project"], name="elora_edges_predica_499dfd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="edge",
            unique_together={("subject", "predicate", "object")},
        ),
    ]
