# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.core.validators
import uuid
from django.db import connection, migrations, models

def _array_or_json(**kwargs):
    """Use ArrayField on PostgreSQL, JSONField on SQLite."""
    if connection.vendor == "postgresql":
        import django.contrib.postgres.fields
        return django.contrib.postgres.fields.ArrayField(**kwargs)
    # Drop base_field/size — not applicable to JSONField
    kwargs.pop("base_field", None)
    kwargs.pop("size", None)
    return models.JSONField(**kwargs)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NPC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="NPC display name", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="NPC description and background",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("in_development", "In Development"),
                            ("ready", "Ready"),
                            ("testing", "Testing"),
                            ("published", "Published"),
                        ],
                        default="concept",
                        help_text="Development status of the NPC",
                        max_length=50,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="NPC age in years",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        help_text="NPC gender identity",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "appearance",
                    models.TextField(
                        blank=True,
                        help_text="Physical appearance description",
                        null=True,
                    ),
                ),
                (
                    "portrait_url",
                    models.URLField(
                        blank=True, help_text="URL to NPC portrait image", null=True
                    ),
                ),
                (
                    "core_traits",
                    models.JSONField(
                        blank=True, default=dict, help_text="Core character traits data"
                    ),
                ),
                (
                    "flag_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of boolean flag names for NPC",
                    ),
                ),
                (
                    "ai_behavior_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="AI behavior configuration"
                    ),
                ),
                (
                    "relationships",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Relationships with other characters",
                    ),
                ),
                (
                    "categories",
                    _array_or_json(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Categories for organization",
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft deletion timestamp", null=True
                    ),
                ),
            ],
            options={
                "db_table": "npcs",
            },
        ),
    ]
