# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("npcs", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="project",
            field=models.ForeignKey(
                help_text="Project this NPC belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="npcs",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["project"], name="npcs_project_5b02d1_idx"),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["status"], name="npcs_status_d3b592_idx"),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["created_at"], name="npcs_created_10db39_idx"),
        ),
        migrations.AddConstraint(
            model_name="npc",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("age__isnull", True), ("age__range", (1, 200)), _connector="OR"
                ),
                name="npc_age_valid_range",
            ),
        ),
    ]
