# Generated by Django 5.0.1 on 2026-04-23 21:30

import apps.common.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npcs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="hidden_from_ui",
            field=models.BooleanField(
                default=False,
                help_text="Hide this NPC from Guide Page, Stats Page, and sidebar NPC-traits widget. Runtime $npcs dict still contains the NPC so prologue/narrative UUID lookups keep working.",
            ),
        ),
        migrations.AlterField(
            model_name="npc",
            name="categories",
            field=apps.common.compat.ArrayField(
                blank=True, default=list, help_text="Categories for organization"
            ),
        ),
    ]
