# Generated by Django 5.0.1 on 2025-11-04 23:05

import apps.stories.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

def _array_or_json(**kwargs):
    """Use ArrayField on PostgreSQL, JSONField on SQLite."""
    if connection.vendor == "postgresql":
        import django.contrib.postgres.fields
        return _array_or_json(**kwargs)
    kwargs.pop("base_field", None)
    kwargs.pop("size", None)
    return models.JSONField(**kwargs)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryCanvas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "canvas_type",
                    models.CharField(
                        choices=[
                            ("story", "Story Canvas"),
                            ("intro", "Introduction Canvas"),
                            ("dialogue", "Dialogue Canvas"),
                            ("tutorial", "Tutorial Canvas"),
                        ],
                        default="story",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    _array_or_json(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("node_count", models.IntegerField(default=0)),
                ("connection_count", models.IntegerField(default=0)),
                (
                    "estimated_play_time",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated play time in minutes",
                        null=True,
                    ),
                ),
                ("is_valid", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_canvases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "story_canvases",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CanvasTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Location where this canvas triggers",
                        null=True,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional trigger conditions",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_activity",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this trigger represents an activity",
                    ),
                ),
                (
                    "is_repeatable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this trigger can repeat over time",
                    ),
                ),
                (
                    "max_triggers_per_day",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times this can trigger per day",
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canvas",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger",
                        to="stories.storycanvas",
                    ),
                ),
            ],
            options={
                "db_table": "canvas_triggers",
            },
        ),
        migrations.CreateModel(
            name="StoryNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("node_data", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    _array_or_json(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "exit_block",
                    models.JSONField(
                        blank=True,
                        default=apps.stories.models.get_default_exit_block,
                        help_text="Configuration for the story node's exit behavior",
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("width", models.FloatField(default=400)),
                ("height", models.FloatField(default=566)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="stories.storycanvas",
                    ),
                ),
            ],
            options={
                "db_table": "story_nodes",
            },
        ),
        migrations.CreateModel(
            name="NodeConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("choice", "Choice"),
                            ("condition", "Conditional"),
                            ("random", "Random"),
                            ("timed", "Timed"),
                            ("hidden", "Hidden"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions for this connection to be available",
                    ),
                ),
                (
                    "effects",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Effects when this connection is traversed",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "path_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="SVG path data for custom routing",
                    ),
                ),
                (
                    "style",
                    models.JSONField(
                        blank=True, default=dict, help_text="Visual styling properties"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority for multiple connections from same node",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0, help_text="Weight for random selection"
                    ),
                ),
                ("is_bidirectional", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="stories.storycanvas",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="stories.storynode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="stories.storynode",
                    ),
                ),
            ],
            options={
                "db_table": "node_connections",
            },
        ),
        migrations.CreateModel(
            name="TriggerSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "weekdays",
                    models.JSONField(
                        help_text="List of weekdays [0-6] where 0=Monday, 6=Sunday"
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="End time for range triggers, null for point triggers",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="stories.canvastrigger",
                    ),
                ),
            ],
            options={
                "db_table": "trigger_schedules",
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "GIF"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.stories.models.media_upload_to),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.stories.models.media_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "media_assets",
                "indexes": [
                    models.Index(
                        fields=["project", "kind"],
                        name="media_asset_project_d165b5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="media_asset_created_2af0bf_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="storycanvas",
            index=models.Index(
                fields=["project", "canvas_type"], name="story_canva_project_682f28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storycanvas",
            index=models.Index(
                fields=["project", "status"], name="story_canva_project_c4f219_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storycanvas",
            index=models.Index(
                fields=["project", "is_favorite"], name="story_canva_project_ba6ce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="canvastrigger",
            index=models.Index(
                fields=["location_id"], name="canvas_trig_locatio_1615f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="canvastrigger",
            index=models.Index(
                fields=["is_active"], name="canvas_trig_is_acti_addb47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storynode",
            index=models.Index(
                fields=["canvas", "created_at"], name="story_nodes_canvas__72fee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeconnection",
            index=models.Index(
                fields=["canvas", "source_node"], name="node_connec_canvas__8b1eb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeconnection",
            index=models.Index(
                fields=["canvas", "target_node"], name="node_connec_canvas__3c6b5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeconnection",
            index=models.Index(
                fields=["canvas", "connection_type"],
                name="node_connec_canvas__bf0757_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="triggerschedule",
            index=models.Index(
                fields=["trigger", "start_time"], name="trigger_sch_trigger_4fe43f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="triggerschedule",
            index=models.Index(
                fields=["start_time", "end_time"], name="trigger_sch_start_t_7b237f_idx"
            ),
        ),
    ]
