# Generated by Django 5.0.1 on 2026-01-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvastrigger",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Higher priority canvases are selected first when multiple are valid. Default 0 for backward compatibility.",
            ),
        ),
    ]
