# Generated by Django 5.0.1 on 2026-02-04 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_add_priority_to_canvas_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storycanvas",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("needs_changes", "Needs Changes"),
                ],
                default="not_submitted",
                help_text="Review/approval status for tracking purposes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="storycanvas",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storycanvas",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_canvases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storycanvas",
            name="review_notes",
            field=models.TextField(blank=True, help_text="Reviewer feedback and notes"),
        ),
    ]
