#!/usr/bin/env python3
"""
guidance_from_ladder.py — one quest card per ladder step, with place and time.

Usage:
    python3 scripts/guidance_from_ladder.py <game-slug>              # TOML to stdout
    python3 scripts/guidance_from_ladder.py <slug> --out PATH        # TOML to a scratch file
    python3 scripts/guidance_from_ladder.py <path/to/game.toml> --state PATH

WHY. The field's best guidance is one line per character step that says WHERE and
WHEN (Round 3 §2.5; being lost is the genre's top complaint). The skill used to key
cards to meter bands, which tells the player a number and not a place. Every step in
`board.characters[].ladder` already declares its canvas, its place and its window, so
the mechanical half of each card is generated here and the author writes only the
words (`the-voice.md` R2).

What it writes, per person with a ladder:
    one card per step n — `when` = counter eq n-1, a goal of counter gte n, a `tip`
    naming the place and the window, `ready_canvas` = the step's canvas, and a
    placeholder `text` (this script writes no prose);
    one terminal card after the last step.

It writes TOML only, to stdout or `--out`, and REFUSES any path inside `games/`: the
author pastes the cards into a phase file after writing their lines. Always exits 0
unless the arguments are wrong.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gates  # noqa: E402

REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
DAYS = gates._PR_DAYS


def _q(s):
    return json.dumps(str(s), ensure_ascii=False)


def days_phrase(days):
    """'every day' · 'weekdays' · 'weekends' · 'Mon, Wed' from day names or 0-6."""
    idx = sorted({d for d in (gates._ladder_day(x) for x in days or []) if d is not None})
    if idx == list(range(7)):
        return "every day"
    if idx == [0, 1, 2, 3, 4]:
        return "weekdays"
    if idx == [5, 6]:
        return "weekends"
    return ", ".join(DAYS[i] for i in idx)


def place_time(step, loc_names):
    where = step.get("where") or ""
    when = step.get("when") or {}
    place = loc_names.get(where) or where or "<place>"
    window = f"{when.get('from', '')}–{when.get('to', '')}".strip("–")
    return f"{place}, {days_phrase(when.get('days'))} {window}".strip()


def cards_for(who, ladder, loc_names, npc_names):
    counter = ladder.get("counter")
    steps = sorted(ladder.get("steps") or [], key=lambda s: s.get("n", 0))
    out = [f"# ── {npc_names.get(who, who)} — {len(steps)} step(s), counter `{counter}` "
           f"(generated by guidance_from_ladder.py; write every <…> before pasting) ──"]
    for s in steps:
        n = s.get("n")
        pt = place_time(s, loc_names)
        out += [
            "",
            "[[quest_cards]]",
            f"npc_id       = {_q(who)}",
            f"text         = {_q('<her line for step ' + str(n) + ' — write it>')}",
            f"tip          = {_q(pt)}",
            f"# her voice, optional — keep the place and the time in it:",
            f"# tip        = {_q('I wonder what he is into… ' + pt)}",
            f"when         = [ {{ type = \"trait\", subject = \"player\", trait = {_q(counter)}, "
            f"op = \"eq\", value = {n - 1} }} ]",
            f"goals        = [ {{ type = \"trait\", subject = \"player\", trait = {_q(counter)}, "
            f"op = \"gte\", value = {n}, label = {_q('<what she does> — ' + pt)} }} ]",
            f"ready_canvas = {_q(s.get('canvas') or '')}",
        ]
    if steps:
        k = steps[-1].get("n")
        out += [
            "",
            "[[quest_cards]]",
            f"npc_id        = {_q(who)}",
            f"text          = {_q('<where she stands with them after the last step — write it>')}",
            f"when          = [ {{ type = \"trait\", subject = \"player\", trait = {_q(counter)}, "
            f"op = \"gte\", value = {k} }} ]",
            "terminal      = true",
            f"terminal_text = {_q('<what the next release opens — the-voice.md R5>')}",
        ]
    return out


def generate(game, state):
    """The TOML text for every declared ladder, or '' when none is declared."""
    loc_names = {l.get("id"): l.get("name") or l.get("id") for l in game.get("locations") or []}
    npc_names = {n.get("id"): n.get("name") or n.get("id") for n in game.get("npcs") or []}
    blocks = []
    for who, lad in gates._declared_ladders(state):
        blocks.append("\n".join(cards_for(who, lad, loc_names, npc_names)))
    return "\n\n".join(blocks) + ("\n" if blocks else "")


def under_games(path):
    games = os.path.realpath(os.path.join(REPO, "games"))
    p = os.path.realpath(path)
    return p == games or p.startswith(games + os.sep)


def main(argv=None):
    args = list(sys.argv[1:] if argv is None else argv)
    opts = {}
    for flag in ("--out", "--state"):
        if flag in args:
            i = args.index(flag)
            opts[flag] = args[i + 1] if i + 1 < len(args) else ""
            del args[i:i + 2]
    if not args:
        print(__doc__)
        return 2
    arg = args[0]
    if arg.endswith(".toml"):
        toml_path = arg
        state_path = opts.get("--state") or os.path.join(
            os.path.dirname(os.path.dirname(arg)), "v2_state.json")
    else:
        toml_path = os.path.join(REPO, "games", arg, "toml_phases", "7_final_game.toml")
        state_path = opts.get("--state") or os.path.join(REPO, "games", arg, "v2_state.json")
    out = opts.get("--out")
    if out is not None and under_games(out):
        print(f"refused: {out} is inside games/ — write to a scratch file and paste the cards "
              f"into a phase file after writing their lines")
        return 2
    if not os.path.exists(toml_path):
        print(f"not found: {toml_path}")
        return 2
    game = gates._load(toml_path)
    state = json.load(open(state_path, encoding="utf-8")) if os.path.exists(state_path) else {}
    text = generate(game, state)
    if not text:
        print("no ladder declared — nothing to generate (board.characters[].ladder, state.md)")
        return 0
    if out:
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {text.count('[[quest_cards]]')} card(s) to {out}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
