# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Location name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Location description"),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("recreational", "Recreational"),
                            ("educational", "Educational"),
                            ("workplace", "Workplace"),
                            ("outdoor", "Outdoor"),
                            ("transport", "Transport"),
                            ("special", "Special"),
                        ],
                        default="generic",
                        help_text="Type of location",
                        max_length=20,
                    ),
                ),
                (
                    "canvas_x",
                    models.FloatField(default=0.0, help_text="Canvas X position"),
                ),
                (
                    "canvas_y",
                    models.FloatField(default=0.0, help_text="Canvas Y position"),
                ),
                (
                    "canvas_width",
                    models.FloatField(default=120.0, help_text="Canvas width"),
                ),
                (
                    "canvas_height",
                    models.FloatField(default=80.0, help_text="Canvas height"),
                ),
                (
                    "is_container",
                    models.BooleanField(
                        default=False, help_text="Can contain other locations"
                    ),
                ),
                (
                    "relative_x",
                    models.FloatField(
                        default=0.0, help_text="Position relative to parent"
                    ),
                ),
                (
                    "relative_y",
                    models.FloatField(
                        default=0.0, help_text="Position relative to parent"
                    ),
                ),
                (
                    "hierarchy_level",
                    models.PositiveIntegerField(
                        default=0, help_text="Nesting depth level"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Location icon", max_length=50, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7, null=True
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional location properties",
                    ),
                ),
                (
                    "accessibility_info",
                    models.JSONField(
                        blank=True, default=dict, help_text="Accessibility information"
                    ),
                ),
                (
                    "is_starting_location",
                    models.BooleanField(
                        default=False, help_text="Is this the starting location"
                    ),
                ),
                (
                    "is_accessible",
                    models.BooleanField(
                        default=True, help_text="Is location accessible"
                    ),
                ),
                (
                    "requires_unlock",
                    models.BooleanField(
                        default=False, help_text="Requires unlock to access"
                    ),
                ),
                (
                    "unlock_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions to unlock location",
                    ),
                ),
                (
                    "supports_realistic_movement",
                    models.BooleanField(
                        default=True, help_text="Supports realistic movement"
                    ),
                ),
                (
                    "requires_realistic_movement",
                    models.BooleanField(
                        default=False, help_text="Requires realistic movement"
                    ),
                ),
                (
                    "navigation_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of location UUIDs for custom navigation display (exit options always appear at bottom)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_entry_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default location when entering this container",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_container",
                        to="world.location",
                    ),
                ),
                (
                    "entry_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="The single location this can be entered from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="can_enter",
                        to="world.location",
                    ),
                ),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent container location",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_locations",
                        to="world.location",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "locations",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(("hierarchy_level__lte", 20)), name="max_hierarchy_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("canvas_width__gte", 50.0), ("canvas_width__lte", 2000.0)
                ),
                name="valid_canvas_width",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("canvas_height__gte", 30.0), ("canvas_height__lte", 2000.0)
                ),
                name="valid_canvas_height",
            ),
        ),
    ]
