# Generated by Django 5.0.1 on 2025-11-04 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Character name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Character description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("development", "Development"),
                            ("complete", "Complete"),
                            ("archived", "Archived"),
                        ],
                        default="concept",
                        help_text="Character development status",
                        max_length=20,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, help_text="Character age (0-200)", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        help_text="Character gender",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "appearance",
                    models.TextField(
                        blank=True, help_text="Physical appearance description"
                    ),
                ),
                (
                    "portrait_url",
                    models.URLField(
                        blank=True,
                        help_text="Character portrait image URL",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "core_traits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Core character traits and values",
                    ),
                ),
                (
                    "flag_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of boolean flag names for player character",
                    ),
                ),
                (
                    "relationships",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Character relationships data",
                    ),
                ),
                (
                    "ai_behavior_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI behavior configuration data",
                    ),
                ),
                (
                    "character_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional character metadata",
                    ),
                ),
                (
                    "game_properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Game-specific character properties",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Character tags for organization",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True, default=list, help_text="Character categories"
                    ),
                ),
                (
                    "development_notes",
                    models.TextField(
                        blank=True, help_text="Character development notes"
                    ),
                ),
                (
                    "inspiration_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Inspiration sources for character",
                    ),
                ),
                (
                    "experience_points",
                    models.PositiveIntegerField(
                        default=0, help_text="Character experience points"
                    ),
                ),
                (
                    "character_level",
                    models.PositiveIntegerField(default=1, help_text="Character level"),
                ),
                (
                    "progression_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Character progression data"
                    ),
                ),
                (
                    "inventory",
                    models.JSONField(
                        blank=True, default=dict, help_text="Character inventory data"
                    ),
                ),
                (
                    "equipment",
                    models.JSONField(
                        blank=True, default=dict, help_text="Character equipment data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "characters",
                "ordering": ["created_at"],
            },
        ),
    ]
