# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0001_initial"),
        ("projects", "0001_initial"),
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Character's current location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="world.location",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_character",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["project"], name="characters_project_7ba42c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["created_at"], name="characters_created_2740c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.CheckConstraint(
                check=models.Q(("age__lte", 200)), name="valid_character_age"
            ),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.CheckConstraint(
                check=models.Q(("character_level__gte", 1)),
                name="valid_character_level",
            ),
        ),
    ]
