# Generated by Django 5.0.1 on 2025-11-04 23:05

import apps.assets.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetClip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.IntegerField()),
                ("start_sec", models.FloatField()),
                ("end_sec", models.FloatField()),
                ("duration_sec", models.FloatField()),
                ("file", models.FileField(max_length=255, upload_to="assets/clips/")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="assets/posters/",
                    ),
                ),
                ("status", models.CharField(default="complete", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "asset_clips",
            },
        ),
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "asset_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=apps.assets.models.assets_upload_to
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="assets/posters/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "asset_videos",
            },
        ),
        migrations.CreateModel(
            name="ClipFrame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp_sec", models.FloatField()),
                (
                    "image_file",
                    models.ImageField(max_length=255, upload_to="assets/frames/"),
                ),
                ("caption_text", models.TextField(blank=True)),
                (
                    "caption_model",
                    models.CharField(default="joycaption2", max_length=100),
                ),
                ("status", models.CharField(default="pending", max_length=16)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "asset_clip_frames",
            },
        ),
    ]
