# Generated by Django 5.0.1 on 2025-11-04 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assetgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetvideo",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="assets.assetgroup",
            ),
        ),
        migrations.AddField(
            model_name="assetclip",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clips",
                to="assets.assetvideo",
            ),
        ),
        migrations.AddField(
            model_name="clipframe",
            name="clip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frames",
                to="assets.assetclip",
            ),
        ),
        migrations.AddIndex(
            model_name="assetgroup",
            index=models.Index(
                fields=["owner", "created_at"], name="asset_group_owner_i_ce01f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetvideo",
            index=models.Index(
                fields=["group", "created_at"], name="asset_video_group_i_281711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetvideo",
            index=models.Index(fields=["status"], name="asset_video_status_9fcc2c_idx"),
        ),
        migrations.AddIndex(
            model_name="assetclip",
            index=models.Index(
                fields=["video", "index"], name="asset_clips_video_i_309692_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetclip",
            index=models.Index(
                fields=["video", "created_at"], name="asset_clips_video_i_923da2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clipframe",
            index=models.Index(
                fields=["clip", "timestamp_sec"], name="asset_clip__clip_id_c668f9_idx"
            ),
        ),
    ]
