# Generated by Django 5.0.1 on 2025-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetclip",
            name="is_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assetclip",
            name="is_uploaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assetclip",
            name="temp_file_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="assetclip",
            name="file",
            field=models.FileField(
                blank=True, max_length=255, upload_to="assets/clips/"
            ),
        ),
        migrations.AlterField(
            model_name="assetvideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready_for_review", "Ready for Review"),
                    ("uploading", "Uploading"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
