# Generated by Django 5.0.1 on 2025-11-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_assetclip_is_selected_assetclip_is_uploaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetvideo",
            name="processing_progress",
            field=models.IntegerField(default=0, help_text="Processing progress 0-100"),
        ),
        migrations.AddField(
            model_name="assetvideo",
            name="processing_stage",
            field=models.CharField(
                blank=True, help_text="Current processing stage", max_length=100
            ),
        ),
    ]
