# Generated by Django 5.0.1 on 2025-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_assetvideo_processing_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipframe',
            name='image_file',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='assets/frames/',
                max_length=255,
                help_text='Optional frame image file. For caption-only extraction, this can be null.'
            ),
        ),
    ]
