# Generated by Django 5.2.6 on 2025-12-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_cleanup_review_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetclip",
            name="is_selected",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetclip",
            name="is_uploaded",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="assetclip",
            name="temp_file_path",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="assetvideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("ready_for_review", "Ready for Review"),
                    ("uploading", "Uploading"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
