# Generated by Django 5.2.6 on 2025-12-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_make_review_fields_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetclip",
            name="is_selected",
        ),
        migrations.RemoveField(
            model_name="assetclip",
            name="is_uploaded",
        ),
        migrations.RemoveField(
            model_name="assetclip",
            name="temp_file_path",
        ),
        migrations.AlterField(
            model_name="assetvideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
