# Generated by Django 5.2.6 on 2025-12-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0008_remove_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetclip",
            name="description",
            field=models.TextField(
                blank=True, help_text="AI-generated description from frame captions"
            ),
        ),
        migrations.AddField(
            model_name="assetclip",
            name="description_error",
            field=models.TextField(
                blank=True, help_text="Error message if generation failed"
            ),
        ),
        migrations.AddField(
            model_name="assetclip",
            name="description_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="When description was generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="assetclip",
            name="description_model",
            field=models.CharField(
                blank=True, help_text="Model used (e.g., grok-4-fast)", max_length=50
            ),
        ),
    ]
