# Generated by Django 5.0.1 on 2025-12-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_add_clip_description_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetclip",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="assetclip",
            index=models.Index(
                fields=["deleted_at"], name="asset_clips_deleted_140a00_idx"
            ),
        ),
    ]
