#!/usr/bin/env python3
"""
Merge phased TOML files into a single buildable game TOML.

Convention (from TLS / prompts_v2 Stage 2 emission at full_game scope):

    games/<game_slug>/toml_phases/
        0_systems_spec.toml             # [project] + [engine.*] + sidebar items
        1_metadata_and_locations.toml   # [[locations]] + [[npcs]] (with schedules + core_traits) + [player]
        2_one_shots.toml                # intro / onboarding [[canvases]]
        3_activities.toml               # Maya-solo dispatcher [[canvases]]
        4_story_arc.toml                # capstones + capstone chain + stage transition [[canvases]]
        5_scenes.toml                   # Lane 1 / Lane 2 / Lane 3 scene [[canvases]]
        6_dev_shortcuts.toml            # dev [[canvases]]
        7_final_game.toml               # OUTPUT — concatenated buildable TOML

Phase 0 + 1 hold top-level singletons ([project], [engine.*], [player]) plus the
nested NPCs/schedules tables (NPCs and schedules must share a file because of
TOML scoping). Phases 2-6 contain ONLY [[canvases]] arrays-of-tables, which can
safely scatter across files.

Usage:

    python scripts/merge_toml_phases.py games/<game_slug>
    python scripts/merge_toml_phases.py games/<game_slug> --validate  # parse with tomllib after merge

The script preserves source comments + ordering. It does NOT re-emit TOML via a
library; it concatenates raw text + adds a phase header before each block. This
keeps the merged file diff-friendly against the phase sources.

After merge, build via:

    python manage.py package_from_toml \\
        --file games/<game_slug>/toml_phases/7_final_game.toml \\
        --owner-id <uuid> \\
        --output games/<game_slug>/output \\
        --dev
"""

import argparse
import sys
from pathlib import Path

PHASE_FILES = [
    "0_systems_spec.toml",
    "1_metadata_and_locations.toml",
    "2_one_shots.toml",
    "3_activities.toml",
    "4_story_arc.toml",
    "5_scenes.toml",
    "6_dev_shortcuts.toml",
]
OUTPUT_FILENAME = "7_final_game.toml"


def merge(game_dir: Path, validate: bool = False) -> Path:
    phases_dir = game_dir / "toml_phases"
    if not phases_dir.is_dir():
        raise SystemExit(f"error: {phases_dir} does not exist")

    parts = [
        f"# {OUTPUT_FILENAME} — merged from phases 0-6 via scripts/merge_toml_phases.py\n",
        f"# Source: {phases_dir}\n",
        "# DO NOT EDIT THIS FILE BY HAND. Edit phases 0-6 and re-merge.\n\n",
    ]

    missing = []
    for phase_filename in PHASE_FILES:
        phase_path = phases_dir / phase_filename
        if not phase_path.is_file():
            missing.append(phase_filename)
            continue
        body = phase_path.read_text()
        parts.append(f"# ══════════════════════════════════════════════════════════════════\n")
        parts.append(f"# Phase: {phase_filename}\n")
        parts.append(f"# ══════════════════════════════════════════════════════════════════\n\n")
        parts.append(body)
        if not body.endswith("\n"):
            parts.append("\n")
        parts.append("\n")

    if missing:
        print(f"warning: missing phase files: {missing}", file=sys.stderr)

    out_path = phases_dir / OUTPUT_FILENAME
    out_path.write_text("".join(parts))
    print(f"merged {len(PHASE_FILES) - len(missing)} phase(s) → {out_path}")
    print(f"  size: {out_path.stat().st_size:,} bytes")

    if validate:
        try:
            import tomllib  # 3.11+
        except ImportError:
            try:
                import tomli as tomllib  # fallback
            except ImportError:
                print("warning: --validate requested but tomllib/tomli not available; skipping", file=sys.stderr)
                return out_path
        try:
            with out_path.open("rb") as fp:
                tomllib.load(fp)
            print(f"  validation: OK (parsed cleanly)")
        except Exception as exc:
            print(f"  validation: FAILED — {exc}", file=sys.stderr)
            raise SystemExit(1)

    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("game_dir", type=Path, help="path to games/<game_slug>/")
    parser.add_argument("--validate", action="store_true", help="parse merged TOML via tomllib after writing")
    args = parser.parse_args()
    merge(args.game_dir, validate=args.validate)


if __name__ == "__main__":
    main()
